<a href="https://colab.research.google.com/github/litlife8582/C/blob/main/Creation_of_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np

In [ ]:
list1={1,2,3,4,5,6}
array1=np.array(list1)
print(array1)

tuple1=(1,2,3,4,5)
arr=np.array(tuple1)
print(arr)

{1, 2, 3, 4, 5, 6}
[1 2 3 4 5]


In [ ]:
#creating a 2D array or list of lists
array2=np.array([[5,7],[6,8]])
print(array2)

[[5 7]
 [6 8]]


Creating Multidimentional Arrays using array creation functions

1D array
np.arrange and np.arange

np.arange

Parameters:

1.start (optional): The starting value of the sequence (default is 0).

2.stop (required): The end value (exclusive).

3.step (optional): The step size between values (default is 1).

4.dtype (optional): The data type of the output array.

Syntax of np.arange function:

numpy.arange([start, ]stop, [step, ], dtype=None)


In [16]:
array4=np.arange(2,10,dtype=float)#prints an array of elements having float datatype with default step size 1
print(array4)

#with stepsize 0.5
array5=np.arange(2,10,0.5,dtype=float)
print(array5)

[2. 3. 4. 5. 6. 7. 8. 9.]
[2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


np.linspace():
numpy.linspace() is used to generate an array of evenly spaced numbers over a specified range.

Parameters:

1.start (required): The starting value of the sequence.

2.stop (required): The end value of the sequence.

3.num (optional, default=50): Number of values to generate.

4.endpoint (optional, default=True): If True, includes stop; if False, excludes it.
5.retstep (optional, default=False): If True, returns the step size along with the array.

6.dtype (optional): Specifies the data type of the output array.



Syntax:

numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)


In [23]:
array6=np.linspace(2,5,num=5,dtype=float)
print(array6)

[2.   2.75 3.5  4.25 5.  ]
